var pl = {
"audio":                          "audio",
"video":                          "wideo",
"playerHeading":                  "Odtwarzacz multimedialny",
"faster":                         "Szybciej",
"slower":                         "Wolniej",
"play":                           "Grać",
"pause":                          "Pauza",
"stop":                           "Zatrzymać",
"restart":                        "Uruchom ponownie",
"prevChapter":                    "Poprzedni rozdział",
"nextChapter":                    "Następny rozdział",
"prevTrack":                      "Poprzedni utwór",
"nextTrack":                      "Następny utwór",
"rewind":                         "Przewijanie do tyłu",
"forward":                        "Naprzód",
"captions":                       "Podpisy",
"showCaptions":                   "Pokaż nagłówki",
"hideCaptions":                   "Ukryj podpisy",
"captionsOff":                    "Wyłączone napisy",
"showTranscript":                 "Pokaż transkrypcję",
"hideTranscript":                 "Ukryj transkrypcję",
"turnOnDescriptions":             "Włącz opisy",
"turnOffDescriptions":            "Wyłącz opisy",
"chapters":                       "Rozdziały",
"newChapter":                     "Nowy rozdział",
"language":                       "Język",
"sign":                           "Język migowy",
"showSign":                       "Pokaż język migowy",
"hideSign":                       "Ukryj język migowy",
"seekbarLabel":                   "oś czasu",
"mute":                           "Niemy",
"unmute":                         "Wyłącz wyciszenie",
"volume":                         "Tom",
"volumeHelp":                     "Kliknij, aby uzyskać dostęp do suwaka głośności",
"volumeUpDown":                   "Zwiększ głośność",
"volumeSliderClosed":             "Suwak głośności zamknięty",
"preferences":                    "Preferencje",
"enterFullScreen":                "Wejdź na pełny ekran",
"exitFullScreen":                 "Wyłączyć tryb pełnoekranowy",
"fullScreen":                     "Pełny ekran",
"speed":                          "Prędkość",
"and":                            "i",
"or":                             "lub",
"spacebar":                       "spacja",
"transcriptTitle":                "Transkrypcja",
"lyricsTitle":                    "tekst piosenki",
"autoScroll":                     "Auto Scroll",
"unknown":                        "Nieznany",
"statusPlaying":                  "Gra",
"statusPaused":                   "Wstrzymany",
"statusStopped":                  "Zatrzymany",
"statusWaiting":                  "Czekanie",
"statusBuffering":                "Buforowanie",
"statusUsingDesc":                "Korzystanie z opisanej wersji",
"statusLoadingDesc":              "Ładowanie opisanej wersji",
"statusUsingNoDesc":              "Korzystanie z wersji nieopisanej",
"statusLoadingNoDesc":            "Ładowanie wersji nieopisanej",
"statusLoadingNext":              "Ładowanie następnego utworu",
"statusEnd":                      "Koniec ścieżki",
"selectedTrack":                  "Wybrana ścieżka",
"alertDescribedVersion":          "Korzystanie z opisanej wersji audio tego filmu",
"alertNonDescribedVersion":       "Korzystanie z nieopisanej wersji tego filmu",
"fallbackError1":                 "Niestety Twoja przeglądarka nie jest w stanie tego odtworzyć",
"fallbackError2":                 "Następujące przeglądarki działają z tym odtwarzaczem multimedialnym",
"orHigher":                       "lub wyżej",
"prefMenuCaptions":               "Podpisy",
"prefMenuDescriptions":           "Opisy",
"prefMenuKeyboard":               "Klawiatura",
"prefMenuTranscript":             "Transkrypcja",
"prefTitleCaptions":              "Preferencje podpisów",
"prefTitleDescriptions":          "Preferencje opisu audio",
"prefTitleKeyboard":              "Preferencje klawiatury",
"prefTitleTranscript":            "Preferencje transkrypcji",
"prefIntroCaptions":              "Następujące preferencje kontrolują sposób wyświetlania podpisów.",
"prefIntroDescription1":          "  Ten odtwarzacz multimedialny obsługuje opis audio na dwa sposoby:",
"prefIntroDescription2":          "Aktualny film ma",
"prefIntroDescriptionNone":       "Bieżący film nie zawiera opisu audio w żadnym z formatów.",
"prefIntroDescription3":          "  Użyj poniższego formularza, aby ustawić preferencje związane z audiodeskrypcją.",
"prefIntroDescription4":          "  Po zapisaniu ustawień opis audio można włączyć / wyłączyć za pomocą przycisku Opis.",
"prefIntroKeyboard1":             "  Odtwarzacz multimedialny na tej stronie może być obsługiwany z dowolnego miejsca na stronie za pomocą skrótów klawiaturowych (lista poniżej znajduje się poniżej).",
"prefIntroKeyboard2":             "  Klawisze modyfikujące (Shift Alt i Control) można przypisać poniżej.",
"prefIntroKeyboard3":             "  UWAGA: Niektóre kombinacje klawiszy mogą kolidować z kluczami używanymi przez przeglądarkę i / lub inne aplikacje. Wypróbuj różne kombinacje klawiszy modyfikujących, aby znaleźć taki, który działa dla Ciebie.",
"prefIntroTranscript":            "  Następujące preferencje wpływają na interaktywny zapis.",
"prefCookieWarning":              "  Zapisywanie preferencji wymaga plików cookie.",
"prefHeadingKeyboard1":           "  Klawisze modyfikujące używane do skrótów",
"prefHeadingKeyboard2":           "Aktualne skróty klawiaturowe",
"prefHeadingDescription":         "Audiodeskrypcja",
"prefHeadingTextDescription":     "Tekstowy opis audio",
"prefHeadingCaptions":            "Podpisy",
"prefHeadingTranscript":          "Interaktywny zapis",
"prefAltKey":                     "Alt",
"prefCtrlKey":                    "Kontrola",
"prefShiftKey":                   "Przesunięcie",
"escapeKey":                      "Ucieczka",
"escapeKeyFunction":              "Zamknij bieżące okno dialogowe lub menu podręczne",
"prefDescFormat":                 "preferowany format",
"prefDescFormatHelp":             "Jeśli oba formaty są dostępne, zostanie użyty tylko jeden.",
"prefDescFormatOption1":          "  alternatywna opisana wersja wideo",
"prefDescFormatOption1b":         "alternatywna opisana wersja",
"prefDescFormatOption2":          "tekstowy opis ogłaszany przez czytnik ekranu",
"prefDescFormatOption2b":         "opis tekstowy",
"prefDescPause":                  "Automatycznie wstrzymaj odtwarzanie wideo po rozpoczęciu opisu",
"prefVisibleDesc":                "Spraw, aby opis był widoczny",
"prefHighlight":                  "Wyróżnij transkrypcję podczas odtwarzania multimediów",
"prefTabbable":                   "Zapis z włączoną klawiaturą",
"prefCaptionsFont":               "Czcionka",
"prefCaptionsColor":              "Kolor tekstu",
"prefCaptionsBGColor":            "tło",
"prefCaptionsSize":               "Rozmiar czcionki",
"prefCaptionsOpacity":            "Nieprzezroczystość",
"prefCaptionsStyle":              "Styl",
"serif":                          "szeryf",
"sans":                           "bezszeryfowy",
"cursive":                        "kursywny",
"fantasy":                        "Fantazja",
"monospace":                      "monospace",
"white":                          "biały",
"yellow":                         "żółty",
"green":                          "Zielony",
"cyan":                           "cyjan",
"blue":                           "niebieski",
"magenta":                        "magenta",
"red":                            "czerwony",
"black":                          "czarny",
"transparent":                    "przezroczysty",
"solid":                          "solidny",
"captionsStylePopOn":             "Pop-on",
"captionsStyleRollUp":            "Roll-up",
"prefCaptionsPosition":           "Pozycja",
"captionsPositionOverlay":        "Narzuta",
"captionsPositionBelow":          "Poniżej wideo",
"sampleCaptionText":              "Przykładowy tekst podpisu",
"prefSuccess":                    "Twoje zmiany zostały zapisane.",
"prefNoChange":                   "  Nie dokonałeś żadnych zmian.",
"help":                           "  Wsparcie",
"helpTitle":                      "Wsparcie",
"save":                           "Zapisać",
"cancel":                         "Anuluj",
"ok":                             "dobrze",
"done":                           "Gotowe",
"closeButtonLabel":               "Zamknij okno dialogowe",
"windowButtonLabel":              "Opcje okna",
"windowMove":                     "Ruszaj się",
"windowMoveAlert":                "Przeciągnij lub użyj klawiszy strzałek, aby przesunąć okno; Enter, aby zatrzymać",
"windowResize":                   "Zmień rozmiar",
"windowResizeHeading":            "Zmień rozmiar okna",
"windowResizeAlert":              "Okno zostało zmienione.",
"windowClose":                    "  Blisko",
"width":                          "Szerokość",
"height":                         "Wysokość",
"windowSendBack":                 "Wyślij do tyłu",
"windowSendBackAlert":            "To okno jest teraz za innymi obiektami na stronie.",
"windowBringTop":                 "  Przesuń na wierzch",
"windowBringTopAlert":            "To okno jest teraz przed innymi obiektami na stronie."
};
